name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: build with Gradle Wrapper
      run: ./gradlew build

    - name: test with Gradle Wrapper
      run: ./gradlew test

    - name: Jar with Gradle Wrapper
      run: ./gradlew jar

    - name: voer uit with Gradle Wrapper
      run: java -cp "build/libs/Opdracht_5-1.0-SNAPSHOT.jar;." be.kuleuven.candycrush "Emre"
